[build-system]
requires = [
    "setuptools >= 42.0.0, <77", # TODO: REMOVE UPPER LIMIT ONCE IT IS ADAPTED ON THE RELEASE ACTION
    "wheel", 
    "ansys_tools_protoc_helper>=0.4.0", 
    "ansys-api-geometry==0.4.54"
    ]
build-backend = "setuptools.build_meta:__legacy__"
