[build-system]
requires = [
    "setuptools >= 42.0.0", 
    "wheel", 
    "ansys_tools_protoc_helper>=0.4.0", 
    "ansys-api-geometry==0.4.10"
    ]
build-backend = "setuptools.build_meta:__legacy__"
